/**
 * The mark: one neuron, two inputs feeding an output, in the chart blue and
 * orange with no tile, so it sits on any background. `mono` draws it in
 * currentColor for places that want a single ink.
 *
 * Generated by dev/logo.mjs. Edit the script, not this file.
 */

export const LOGO_BLUE = '#0f7ea3';
export const LOGO_ORANGE = '#f59322';

export function LogoMark({
  size = 24,
  className,
  mono = false,
}: {
  size?: number;
  className?: string;
  mono?: boolean;
}) {
  const ink = mono ? 'currentColor' : LOGO_BLUE;
  const out = mono ? 'currentColor' : LOGO_ORANGE;
  return (
    <svg
      className={className}
      width={size}
      height={size}
      viewBox="0 0 32 32"
      aria-hidden="true"
      focusable="false"
    >
      <g fill={ink} stroke={ink} strokeWidth={3} strokeLinecap="round">
        <path d="M 7 8 L 24 16 M 7 24 L 24 16" fill="none"/>
        <circle cx="7" cy="8" r="4"/>
        <circle cx="7" cy="24" r="4"/>
      </g>
      <circle cx="24" cy="16" r="6.5" fill={out} />
    </svg>
  );
}

/** Mark plus wordmark, the header and footer lockup. */
export function Logo({ size = 24 }: { size?: number }) {
  return (
    <span className="mlx-logo">
      <LogoMark size={size} />
      <span className="mlx-logo__text">Interactive&nbsp;ML</span>
    </span>
  );
}
